'use strict';

// Declare app level module
angular.module('dapoll', [
  'dapoll.common',
  'dapoll.pages',
  'dapoll.templates' // dynamically generated by grunt-angular-templates
]);

angular.module('dapoll')

  .config(function ($locationProvider, $urlRouterProvider) {
    
    $urlRouterProvider.otherwise('/');

    // enable the HTML5 push/pop history API  
    $locationProvider.html5Mode(true);
  })
  
  .run(function ($rootScope, $state, $stateParams) {
    $rootScope.$state = $state;
    $rootScope.$stateParams = $stateParams;
  });

// This module will be used by grunt-angular-templates to add all templates to cache
angular.module('dapoll.templates', []);